// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.41.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<XelisWallet> createXelisWallet(
        {required String name,
        required String password,
        String? seed,
        String? precomputedTablesPath}) =>
    RustLib.instance.api.crateApiWalletCreateXelisWallet(
        name: name,
        password: password,
        seed: seed,
        precomputedTablesPath: precomputedTablesPath);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<XelisWallet>>
abstract class XelisWallet implements RustOpaqueInterface {
  Stream<String> eventsStream();
}
